### ISSUE TITLE
ordered ascending by date posted is not working

### ISSUE THREAD

**Issue by kevinyin9** [Yukigeshiki/job-hunt-rust#93]
Thanks for creating such useful tools!

But the date is not ordered.
![Snipaste_2023-09-21_17-05-18](https://github.com/Yukigeshiki/job-hunt-rust/assets/20009750/df5fe648-01e7-4767-a8ae-9649ece46eee)

**Comment by kevinyin9** [comment]
Sorry. I misunderstood the order.

**Comment by Yukigeshiki** [comment]
No problem. I'm glad you are finding it useful! :)
